title: My Portfolio
description:
email: o.silkin98@gmail.com
github_username: osilkin98

show_downloads: true
theme: jekyll-theme-slate
plugins:
  - jekyll-feed
  - github-pages

markdown: kramdown
kramdown:
  parse_block_html: true
